import React, { useEffect, useState, useCallback, useRef } from "react";
import { Link } from 'react-router-dom'; 
import {   Button, 
  Typography, 
  Container, 
  Box, 
  Paper,
  CardContent,
  Dialog,
  DialogTitle,
  DialogContent,
  TextField,
  DialogActions,
  CircularProgress,
  Collapse, 
  Checkbox, FormControlLabel, FormGroup,
  IconButton, IconButtonProps,
  Fade,
  Menu, MenuProps, MenuItem,
  Select, SelectChangeEvent } from '@mui/material';
import Multiselect from 'multiselect-react-dropdown';
import { AnimatedBackground, useAnimationControls } from 'animated-backgrounds';
import { styled } from '@mui/system';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import emailjs from 'emailjs-com';
import { keyframes } from "@mui/system";
import axios from "axios";

// VideoPairApp.jsx
let demographicsData = {"age": 0, "highestDegree": "", "country": "", "hobbies": "", "profession": ""};
let rankedVideos = {};
let selectionTimes = {};
let notSelectionTimes = {};
let resultsFile = "";
let resultsName = "";
const REGISTRATION_API_URL = "https://netlogo-survey-registration.onrender.com";


export default function VideoPairApp_simple() {
  // CSS components
  const body = {
    height: "100%",
    width: "100%",
    border: "10px solid transparent",
    borderImage: "url(https://vultimate1.github.io/grid-electronics.png)",
    borderImageRepeat: "round",
    transition: "background-color 0.8s ease",
    boxSizing: "border-box",
  };

  // states
  const [complete, setComplete] = useState(false); // has user completed survey already
  const [userEmail, setUserEmail] = useState(null); // user email
  const [userIPAddress, setUserIPAddress] = useState("");
  const [startInstructions, setStartInstructions] = useState([]); // reading the opening instructions
  const [preSurvey, setPreSurvey] = useState([]); // reading the pre-survey instructions
  const [samplePair, setSamplePair] = useState(false); // display sample pair
  const [selectedSample, setSelectedSample] = useState(false); // display sample pair
  const [initSurvey, setInitSurvey] = useState(); // start the survey
  const startedSurvey = useRef(false); // determine when to start main survey
  const [items, setItems] = useState([]); // full list loaded from JSON
  const [loading, setLoading] = useState(true); // is the data loading
  const [countries, setCountries] = useState([]); // getting countries from excel file
  const [languages, setLanguages] = useState([]); // getting languages from excel file
  const [professions, setProfessions] = useState([]); // getting professions from excel file
  const [demographics, setDemographics] = useState(true); // show form for getting user demographic info
  const [errors, setErrors] = useState({}); // finding errors in demographics survey response
  const [startvid, setStartvid] = useState(""); // set the starting video
  const [behavior, setBehavior] = useState(""); // set the behavior to be used in the video
  const [surveyVids, setSurveyVids] = useState([]); // setting the videos to be used in the survey
  const [pool, setPool] = useState([]); // shuffled remaining items
  const [pair, setPair] = useState([]); // current pair of two items
  const [pairs, setPairs] = useState([]); // all pairs of videos as generated by the pool of videos
  const [current, setCurrent] = useState([]); // setting the chosen video
  const [current_video_pair, set_current_video_pair] = useState({}); // setting the pair of videos the survey is on
  const [current_video_names, set_current_video_names] = useState({}); // getting the names of the videos in the current pair
  const [chosenVids, setChosenVids] = useState([]);
  const [notChosenVids, setNotChosenVids] = useState([]);  
  const [results, setResults] = useState([]); // recorded choices: {left, right, chosenId}
  const [ended, setEnded] = useState(false); // has the survey been completed?
  const [start, setStart] = useState(() => performance.now()); // is the survey starting?
  const [reloadKey, setReloadKey] = useState(0); // reloading video reference
  const [choiceTime, setChoiceTime] = useState(0); // what is the start time?
  const [times, setTimes] = useState([]); // array for the times taken by each user
  const [vidnum, setVidnum] = useState(1); // increment number of videos seen
  const [vid_indices, set_vid_indices] = useState([]); // indices of each video
  const [rankings, setRankings] = useState([]); // ordered ranked videos after the survey
  const [display, setDisplay] = useState(0); // choose which results to display: rankings or the times
  const [numChanges, setNumChanges] = useState(0); // this is used to determine which results to display
  const [titleFloat, setTitleFloat] = useState(false); // for floating animation for a header
  const [betas, setBetas] = useState({}); // bradley-terry probabilities of the next videos being selected
  const [numVideos, setNumVideos] = useState(0);
  const specificBehavior = "maxalignturn-mod";

const getIP = async() => {
  try {
    const response = await fetch("https://swarm-backend-ga0y.onrender.com/ip");
    console.log("after response sent");
    if (!response.ok) {
      throw new Error(`HTTP error: status ${response.status}`);
    }  
    const data = await response.json();
    console.log("IP address is: ", data.ip);
    setUserIPAddress( data.ip );
  } catch (error) {
    console.log("Failed to fetch IP address: "+ error);
  }	
};

useEffect(() => {
  if (userIPAddress) {
    console.log("User IP is now:", userIPAddress);
  }
}, [userIPAddress]);

useEffect(() => {
  getIP();
  
  // fetch user email
  const params = new URLSearchParams(window.location.search);
  const fetched_email = params.get('email');
  if (fetched_email) {
    setUserEmail(decodeURIComponent(fetched_email));
  }

  // Timing background render upon survey start up
  const timer = setTimeout(() => {
    setTitleFloat(true);
  }, 50); // small delay ensures first render happens at opacity 0
  return () => clearTimeout(timer);
}, []);

useEffect(() => {
  if (!userEmail) return;
  fetch(`${REGISTRATION_API_URL}/check-completed?email=${encodeURIComponent(userEmail)}`)
    .then(res => res.json())
    .then(data => setComplete(data.completed ? true : false))
    .catch(() => setComplete(false)); // decide fail-open vs fail-closed
  console.log("is it complete? ", complete);
}, [userEmail]);

// displaying instructions
useEffect(() => {
  setVisible(false);
  setTimeout(() => {
    setVisible(true);
  }, 500);
}, [startInstructions]);


// title text floats into screen
useEffect(() => {
  setTitleFloat(false);
  setTimeout(() => {
    setTitleFloat(true);
  }, 1000);
}, [display]);


  var text = ""; // display text at the end
  const startTimeRef = useRef(performance.now());
 

  // gets the starting video for behavior selection
  useEffect(() => {
     setTimeout(() => {
     if (!startvid) return;
     console.log("starting video is " +startvid);
     }, 1000);
  }, [startvid]);


  // Utility: shuffle array (Fisher-Yates)
  const shuffle = (arr) => {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    console.log("shuffled first: id:"+String(a[0].id)+", name: "+String(a[0].name));
    return a;
  };

  
  // Build a public URL for a video entry. Assumes video entries in json use paths relative to public/, e.g. "swarm-videos/foo.mp4".
  const makeUrl = (id) => {
    // process.env.PUBLIC_URL is set by CRA at build time; during dev it's empty string
    const base = process.env.PUBLIC_URL;
    // ensure leading slash if PUBLIC_URL empty
    const prefix = base === "" ? "" : base;
    return `${prefix}/${id}`.replace("/\/g", "/");
  };


  useEffect(() => {
     const loadExcel = async() => {
        const ExcelJS = require('exceljs');
        const res = await fetch(process.env.PUBLIC_URL + '/demographics_options.xlsx');
    
        const buffer = await res.arrayBuffer();
        const workbook = new ExcelJS.Workbook();
        await workbook.xlsx.load(buffer);
        const sheet = workbook.worksheets[0]; // get first sheet

        // get countries
        const datacountries = sheet.getColumn('A').values.slice(2); // array of rows
        const countryList = datacountries.flat().filter(Boolean);             // flatten to 1D list
        setCountries(countryList);

        // get hobbies
        const datahobbies = sheet.getColumn('B').values.slice(2); // array of rows
        const hobbiesList = datahobbies.flat().filter(Boolean);             // flatten to 1D list
        setLanguages(hobbiesList);

        // get professions
        const dataprofessions = sheet.getColumn('C').values.slice(2); // array of rows
        const professionsList = dataprofessions.flat().filter(Boolean);             // flatten to 1D list
        setProfessions(professionsList);
     };
     loadExcel();
  }, [demographics]);
  
  // fetch videos from list based on behavior
  function indexExcluding(arr_len, index) {
    if (arr_len <= 1) return null;
    const indices = [];
    for (var i=0; i<arr_len; i++) {
      if (i!=index) {
        indices.push(i);
      }
    }
    console.log("what are indices? "+String(indices));
    set_vid_indices(indices);
  }


// Calculate the probabilities of each video pair as per the Bradley-Terry Method
const btProbability = (beta_i, beta_j) => {
  return Math.exp(beta_i) / (Math.exp(beta_i) + Math.exp(beta_j));
};

const floatFadeIn = keyframes`
  from {
    opacity: 0;
    transform: translateY(-30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
`;

// generate the pairs of videos according to the list of videos for the probabilistic selection of videos as per the Bradley-Terry method
function generatePairs(videos) {
  console.log("WE HAVE "+ (videos).length + " VIDEOS");
  const p = [];
  for (let i = 0; i < videos.length; i++) {
    for (let j = i + 1; j < videos.length; j++) {
      p.push([videos[i], videos[j]]);
    }
  }
  console.log("WE HAVE "+p.length + " PAIRS");
  return p;
}

  // Load json list from JSON video list
  const loadVideos = async() => {
    let mounted = true;
      try {
        setLoading(true);
        console.log("LOADING");
        const res = await fetch(`${process.env.PUBLIC_URL}/video_paths.json`);
        if (!res.ok) throw new Error("Failed to fetch json-videos.json: " + res.status);
        const data = await res.json();
        if (!mounted) return;
        // Normalize: ensure each item has id and name and url

        setItems(data.map((it, idx) => ({
          ...it,
          _idx: idx,
          id: it.id || String(idx),
          url: makeUrl((it.id || String(idx))),
        })));
        // gets the probability values for each video in the survey ranking
        const betavals = {};
        items.forEach(v => {
          betavals[v.id] = 0;
        });
        setBetas(betavals);
        setNumVideos(pairs.length);
        console.log("pairs length: "+pairs.length);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    return () => {(mounted = false)};
  };  


// called by loadVideos(), where the first item matching the selected behavior is set to get the survey starting video
useEffect(() => {
  if (items.length > 0 && !startedSurvey.current) {
    var i=0;
    while (items[i].id.split("/")[2] != specificBehavior) {
      i = i+1;
    }
    startSurvey(items[i]);
  }
}, [items]);

// loads the videos that will be used for the survey and sets the timer
useEffect(() => {
  loadVideos();
  startTimeRef.current = performance.now();
  setStart(performance.now());
}, [initSurvey]);

  function startSurvey(video) {
        /* order each video based on complexity for a selected behavior category */
        // choose swarm behavior
        console.log("IN THE START SURVEY");
        if (startedSurvey.current) return;
        startedSurvey.current = true;
        setBehavior(video.id.split("/")[2]);
        
        setStartvid(video);
        console.log("behavior is "+String(behavior));
  }

// Error checking for each question
  const validate = () => { // checks to see if all required questions are filled out
       const recentErrors = {};
       console.log("inside validate\n");
       console.log(demographicsData);
       if (demographicsData["age"] == 0 || demographicsData["age"] == "Age") recentErrors.age = "Please select an age range.";
       if (demographicsData["highestDegree"] == "" || demographicsData["highestDegree"] == "Degree") recentErrors.highestDegree = "Please select from the dropdown the highest degree you have attained.";
       if (demographicsData["numLanguages"] <= 0 || !Number.isInteger(Number(demographicsData["numLanguages"]))) recentErrors.numLanguages = "Entry must be a number greater than 0.";
       if (demographicsData["hobbies"] == "" || demographicsData["hobbies"] == "Enter hobbies") recentErrors.hobbies = "Please enter any hobbies you have.";
       if (demographicsData["profession"] == "" || demographicsData["profession"] == "Professions") recentErrors.profession = "Please enter your current profession from the dropdown.";
       console.log(demographicsData);
       console.log(recentErrors);
       setErrors(recentErrors);
       return Object.keys(recentErrors).length === 0; // check if number of errors is zero.
  };


useEffect(() => {
  if (!behavior || !items.length) return;

  const filtered = items.filter(v => v.id.includes(behavior));
  console.log("Filtered survey vids:", filtered.length, filtered);

  if (filtered.length < 2) {
    console.warn("Not enough videos to compare for behavior:", behavior);
    //setSurveyVids([]);
    setEnded(true);
    return;
  }
  setSurveyVids(filtered);

  const p = generatePairs(filtered);
  var sorted = [...p].sort(() => Math.random() - 0.5); // shuffle
  console.log("behavior is "+behavior);
  setPairs(sorted);
  for (var i=0; i<sorted.length; i++) {
    console.log(sorted[i]);
  }
  setPair(pairs[0]);
  setNumVideos(sorted.length);
  console.log("in behaviors and items: "+numVideos);

  for (var i=0; i<pairs.length; i++) {
    console.log(pairs[i]);
  }
}, [behavior, items]);


useEffect(() => {
  if (surveyVids.length < 2) {
    setPair([]);
    setPool([]);
    setEnded(true);
    return;
  }
  
  const shuffled = shuffle(surveyVids);
  console.log("shuffled:");
  console.log(shuffled);
  setCurrent(shuffled[0]);
  //setPair([shuffled[0], shuffled[1]]);
  setPair(pairs[vidnum]);
  setPool(shuffled);
  //setPool(shuffled.slice(2));
  setEnded(false);
  setResults([]);
  setTimes([]);
  setChosenVids([]);
  setNotChosenVids([]);
  setVidnum(1);
}, [surveyVids]);

const [visible, setVisible] = useState(true);

const onChoose = useCallback((chosenSide) => {
  if (!pair || pair.length !== 2) return;

  const now = performance.now();
  const elapsed = (now - startTimeRef.current)/1000;

  const left = pair[0];
  const right = pair[1];
  const chosen = chosenSide === "left" ? left : right;
  const notChosen = chosenSide === "right" ? left : right;

  setResults(r => [...r, { left: left.id, right: right.id, chosen: chosen.id, notChosen: notChosen.id, timestamp: Date.now(), elapsedTime: elapsed }]);
  setTimes(t => [...t, elapsed]); 
  setChosenVids(c => [...c, chosen.id]); 
  setNotChosenVids(n => [...n, notChosen.id]); 
  if (pool.length === 0) {
    setEnded(true);
    setPair([]);
    return;
  }

  const alpha = 0.5;

setBetas(prev => {
  const beta_i = prev[chosen.id];
  const beta_j = prev[notChosen.id];

  const p = Math.exp(beta_i) / (Math.exp(beta_i) + Math.exp(beta_j));

  const new_i = beta_i + alpha * (1 - p);
  const new_j = beta_j - alpha * (1 - p);

  return {
    ...prev,
    [chosen.id]: new_i,
    [notChosen.id]: new_j
  };
});

  const nextPair = pairs[0];
  if (!nextPair) {
    setEnded(true);
    setPair([]);
    return;
  }
  setVisible(false);
  setTimeout(() => {
    setCurrent({ chosen, notChosen, elapsed });
    startTimeRef.current = (performance.now());

    set_current_video_pair({
      chosen,
      notChosen,
      elapsed,
    });
    setPairs(p => p.slice(1)); // remove the current pair from the set of pairs to display
    setPair(nextPair); // set current pair to top pair
    //setPool(p => p.slice(1)); 
    setVidnum(v => v + 1); // increment pair number 
    console.log("pool is now: ");
    console.log(pool);
    console.log("pairs are now: ");
    console.log(pairs);
    setVisible(true);
  }, 500);
  setStart(performance.now());
}, [pair, pool]);

// add current to ranked videos
useEffect(() => {
  if (!current_video_pair) return;
  const {chosen, notChosen, elapsed} = current_video_pair;
  if (!chosen || !notChosen) return;
  console.log("chosen video is "+chosen.id+", "+chosen.name);
  console.log("unchosen video is "+notChosen.id+", "+notChosen.name);
  //console.log("times length is "+String(times.length));
  setRankings((prev) => { // ordering from least to most complex
    //console.log("number of rankings? "+String(rankings.length));
    const ranking = [...prev];
    // inserting the newly selected video into list of ranked videos
    let chosenVidIndex = ranking.findIndex((v) => v.id == chosen.id);
    let notChosenVidIndex = ranking.findIndex((v) => v.id == notChosen.id);
    if (chosenVidIndex == -1 && notChosenVidIndex != -1){ // if chosen video not in rankings yet
      ranking.splice(notChosenVidIndex-1,0,chosen); 
      chosenVidIndex = ranking.length - 1; // set as back
    } 
    if (notChosenVidIndex == -1 && chosenVidIndex != -1){
      ranking.splice(chosenVidIndex,0,notChosen);
      notChosenVidIndex = ranking.length - 1; // set as back
    } 
    else if (chosenVidIndex == -1 && notChosenVidIndex == -1){
      ranking.splice(0,0,notChosen);
      ranking.splice(1,0,chosen);
    }
    //ranking.forEach(v => console.log("ranking: "+String(v.id)));
    return ranking;
  });
  setStart(performance.now());
}, [current_video_pair]);


  // keyboard support: ArrowLeft picks left, ArrowRight picks right
  useEffect(() => {
    setTitleFloat(false);
    const handler = (e) => {
      if (ended || loading) return;
      if (e.key === "ArrowLeft") onChoose("left");
      if (e.key === "ArrowRight") onChoose("right");
    };
    window.addEventListener("keydown", handler);
    rankings.forEach((video, index) => {
      rankedVideos[video.id] = index;
      //console.log("ended id: "+video+", index: "+index);
    });
      setTimeout(() => {
         setTitleFloat(true);
      }, 1000); // small delay ensures first render happens at opacity 0
    return () => window.removeEventListener("keydown", handler);
  }, [ended, loading, pair]);

function shuffleNoConsecutive(arr) { // important to ensure that the same behavior of swarm is not shown more than once, ChatGPT provided function
  if (arr.length <= 1) return arr.slice();

  // Copy array to avoid mutation
  let result = [];
  let temp = arr.slice();

  // Helper function to pick a random element not equal to prev
  function pickRandomExcluding(exclude) {
    const filtered = temp.filter(x => x !== exclude);
    if (filtered.length === 0) return null; // no option but to pick exclude
    const choice = filtered[Math.floor(Math.random() * filtered.length)];
    return choice;
  }

  // Start by picking any element randomly
  let prev = null;

  while (temp.length > 0) {
    let choice = pickRandomExcluding(prev);

    // If no other option, pick prev (will create consecutive duplicate)
    if (choice === null) {
      choice = prev;
    }

    // Remove the choice from temp (one occurrence)
    const index = temp.indexOf(choice);
    temp.splice(index, 1);

    result.push(choice);
    prev = choice;
  }

  return result;
}

  const restart = () => {
    console.log("in restart");
    var s = shuffleNoConsecutive(items);
    var behavior = s[0].id.split("/")[2];
    while (behavior === "unknown") {
      console.log("Nope it's unknown");
      s = shuffleNoConsecutive(items);
      behavior = s[0].id.split("/")[2];
    }
    setBehavior(s[0].id.split("/")[2]);
    setBehavior(specificBehavior);
    console.log("Number of items is "+String(items.length));
    console.log("Item first is "+s[0].url);
    setPool(s);
    if (s.length >= 2) {
      console.log("set pair to first two");
      setPair([s[0], s[1]]);
      setPool(prev => {
        // compute new pool from current state if needed
        return s.slice(2);
      });
    } else {
      console.log("just list is s");
      setPair(s);
      setPool([]);
    }
    setResults([]);
    setRankings([]);
    setVidnum(1);
    setPairs(p => p.slice(1));
    rankedVideos = {};
    selectionTimes = {};
    notSelectionTimes = {};
    setInitSurvey(true);

    if (numVideos == 0 && sorted.length > 0) {
       location.reload()
    }
    
    console.log("behavior: "+behavior);
    setEnded(false);
    setTitleFloat(false);
    console.log("setting float");
    setStart(performance.now());
  };

  useEffect(() => {
    setDisplay((n) => ( (n+1)%2 ));
  }, [numChanges]);

  function disp(time) {
    text += String(time) + ",";
  }
  if (complete) {
    return (
      <div style={{ justifyContent: 'flex-start', alignItems: 'center', flexDirection: 'column', display: 'flex', width: '100%', minHeight: '100vh', overflowX: 'hidden', background: `url('general-white-blue.jpg')`, transition: 'background-image 0.5s ease', backgroundSize: '100% 100%, 100% 100%, contain', backgroundPosition: 'center, center, center', backgroundRepeat: 'no-repeat, no-repeat, no-repeat', backgroundBlendMode: 'multiply',}}>
         <Box sx={{
           width: '100%',
           height: 'flex',
           display: 'flex',
           backgroundColor: "rgba(0,0,0,0.5)",
           position: 'fixed', top:'0px', left: '0px', 
         }}>
           <Box 
              component="img"
              sx={{height:'50px',alignItems:'center',justifyContent:'center',display:'flex',top:'0px',left:'0px',}}
              src={`${process.env.PUBLIC_URL}/exalabs-logo.png`}
           />
           <Box sx={{ justifyContent: 'flex-start', alignItems: 'center', }}>
              <Typography sx={{  fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 25, }}>
		You have already completed this survey as {' '} <strong>{userEmail}</strong> 
              </Typography>
           </Box>
         </Box>
      </div>
    );
  }
  if (startInstructions) {
    return (
      <div style={{ justifyContent: 'flex-start', alignItems: 'center', flexDirection: 'column', display: 'flex', width: '100%', minHeight: '100vh', overflowX: 'hidden', background: `url('general-white-blue.jpg')`, transition: 'background-image 0.5s ease', backgroundSize: '100% 100%, 100% 100%, contain', backgroundPosition: 'center, center, center', backgroundRepeat: 'no-repeat, no-repeat, no-repeat', backgroundBlendMode: 'multiply',}}>
      <Box sx={{
         width: '100%',
         height: 'flex',
         display: 'flex',
         backgroundColor: "rgba(0,0,0,0.5)",
 	 position: 'fixed', top:'0px', left: '0px', 
      }}>
         <Box 
            component="img"
            sx={{height:'50px',alignItems:'center',justifyContent:'center',display:'flex',top:'0px',left:'0px',}}
            src={`${process.env.PUBLIC_URL}/exalabs-logo.png`}
         />
         <Typography sx={{ margin: '15px', fontFamily: "'DM Mono', monospace", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.16em', textTransform: 'uppercase', color: '#FFF', borderLeft: '50px solid rgba(0,0,0,0)', position: 'fixed', top:'0px',  }}> Exalabs UMass Lowell </Typography>
      </Box>
        <MainHeader fadeAnimation={titleFloat} />
        <Box sx={{justifyContent: 'center', display: 'flex', flexDirection: 'column',}}>
            <Button sx={{ margin: '48px 0 0', backgroundColor: "#FFF", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.15em', textTransform: 'uppercase', color: '#9a9690', border: '1px solid rgba(26,25,23,0.2)', borderRadius: '4px', padding: '10px 28px', '&:hover': { color: '#1a1917', borderColor: '#2a2a8c', backgroundColor: 'transparent' }, }} variant="contained" onClick={() => {
                 // goes to the tutorial screen
                 setStartInstructions(false);
                 setPreSurvey(true);
                 setTitleFloat(true);
            }}>
                 <Typography sx={{ fontSize: 20, fontFamily: "'Cormorant Garamond', Georgia, serif"}}> <strong>Instructions</strong> </Typography>
            </Button>

        </Box>
        <Button sx={{ margin: '48px 0 0', backgroundColor: "#FFF", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.15em', textTransform: 'uppercase', color: '#9a9690', border: '1px solid rgba(26,25,23,0.2)', borderRadius: '4px', padding: '10px 28px', '&:hover': { color: '#1a1917', borderColor: '#2a2a8c', backgroundColor: 'transparent' }, }} variant="contained" onClick={() => {
           // goes to the next screen for getting user demographics
           console.log("clicked the start");
           setStartInstructions(false);
           setPreSurvey(false);
           setDemographics(true);
           setTitleFloat(true);
        }}>
             <Typography sx={{ fontSize: 20, fontFamily: "'Cormorant Garamond', Georgia, serif"}}> <strong>Start</strong> </Typography>
        </Button>
      </div>
    );
  }
  if (preSurvey) {
    return (
      <div style={{ justifyContent: 'flex-start', alignItems: 'center', flexDirection: 'column', display: 'flex', width: '100%', minHeight: '100vh', overflowX: 'hidden', background: `url('general-white-blue.jpg')`, transition: 'background-image 0.5s ease', backgroundSize: '100% 100%, 100% 100%, contain', backgroundPosition: 'center, center, center', backgroundRepeat: 'no-repeat, no-repeat, no-repeat', backgroundBlendMode: 'multiply',}}>
      <Box sx={{
         width: '100%',
         height: 'flex',
         display: 'flex',
         backgroundColor: "rgba(0,0,0,0.5)",
 	 position: 'fixed', top:'0px', left: '0px', 
      }}>
         <Box 
            component="img"
            sx={{height:'50px',alignItems:'center',justifyContent:'center',display:'flex',top:'0px',left:'0px',}}
            src={`${process.env.PUBLIC_URL}/exalabs-logo.png`}
         />
         <Typography sx={{ margin: '15px', fontFamily: "'DM Mono', monospace", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.16em', textTransform: 'uppercase', color: '#FFF', borderLeft: '50px solid rgba(0,0,0,0)', position: 'fixed', top:'0px',  }}> Exalabs UMass Lowell </Typography>
      </Box>
      <InstructionBoard msgs={ presurvey_messages } nextLink={samplePair} setNextLink={setSamplePair} currLink={preSurvey} setCurrLink={setPreSurvey} nextText={"next"} textSize={"25px"}/>
      </div>
    );
  }
  if (samplePair) { // display a sample pair for the user to select from
      return (
          <div style={{ justifyContent: 'center', flexDirection: 'column', display: 'flex', width: '100%', minHeight: '100vh', overflowX: 'hidden', background: '#f5f3ef', transition: 'background-color 0.5s ease', }}>
    <div style={{ fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial", alignItems: 'stretch', }}>
      <div>
      <Box sx={{
         width: '100%',
         height: 'flex',
         display: 'flex',
         backgroundColor: "rgba(0,0,0,0.5)",
         position: 'fixed',top:'0px',
         zIndex: 100,
         padding: '0 24px',
      }}>
         <Box 
            component="img"
            sx={{height:'50px',alignItems:'center',justifyContent:'center',display:'flex', position: 'fixed',top:'0px',left:'0px',}}
            src={`${process.env.PUBLIC_URL}/exalabs-logo.png`}
         />
         <Typography sx={{ margin: '13px', fontFamily: "'DM Mono', monospace", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.16em', textTransform: 'uppercase', color: '#FFF', borderLeft: '20px solid rgba(0,0,0,0)', }}> Exalabs UMass Lowell </Typography>
      </Box>   
      <Box sx={{ display: 'flex', flexDirection: 'column', textAlign: 'center', alignItems: 'center', justifyContent: 'center', fontSize: 25, padding: '60px', margin: '0 auto', color: '#000' }}>
        <span style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 25, }}>Click the video you think is{' '} <strong>more complex</strong></span>&nbsp;
      </Box>
      
      <div style={{ display: "flex", gap: 12, alignItems: "stretch" }}>
        <VideoCard item={pair[0]} reloadKey={reloadKey} setReloadKey={setReloadKey} onChoose={() => {setSelectedSample(true); setDemographics(false); setSamplePair(false);}} position="left" fadeAnimation={visible} />
        <VideoCard item={pair[1]} reloadKey={reloadKey} setReloadKey={setReloadKey} onChoose={() => {setSelectedSample(true); setDemographics(false); setSamplePair(false);}} position="right" fadeAnimation={visible} />
      </div> 

      </div>
      
    </div>
    </div>
    );
  }
  if (selectedSample) {
    return (
      <div style={{ justifyContent: 'flex-start', alignItems: 'center', flexDirection: 'column', display: 'flex', width: '100%', minHeight: '100vh', overflowX: 'hidden', background: `url('general-white-blue.jpg')`, transition: 'background-image 0.5s ease', backgroundSize: '100% 100%, 100% 100%, contain', backgroundPosition: 'center, center, center', backgroundRepeat: 'no-repeat, no-repeat, no-repeat', backgroundBlendMode: 'multiply',}}>
      <Box sx={{
         width: '100%',
         height: 'flex',
         display: 'flex',
         backgroundColor: "rgba(0,0,0,0.5)",
 	 position: 'fixed', top:'0px', left: '0px', 
      }}>
         <Box 
            component="img"
            sx={{height:'50px',alignItems:'center',justifyContent:'center',display:'flex',top:'0px',left:'0px',}}
            src={`${process.env.PUBLIC_URL}/exalabs-logo.png`}
         />
         <Typography sx={{ margin: '15px', fontFamily: "'DM Mono', monospace", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.16em', textTransform: 'uppercase', color: '#FFF', borderLeft: '50px solid rgba(0,0,0,0)', position: 'fixed', top:'0px',  }}> Exalabs UMass Lowell </Typography>
      </Box>
      <InstructionBoard msgs={ final_message } nextLink={demographics} setNextLink={setDemographics} currLink={selectedSample} setCurrLink={setSelectedSample} nextText={"start"} textSize={"25px"} />
      </div>
    );
  }
  if (demographics) {
    return (
      <div style={{ justifyContent: 'flex-start', alignItems: 'center', flexDirection: 'column', display: 'flex', width: '100%', minHeight: '100vh', overflowX: 'hidden', background: `url('general-white-blue.jpg')`, transition: 'background-image 0.5s ease', backgroundSize: '100% 100%, 100% 100%, contain', backgroundPosition: 'center, center, center', backgroundRepeat: 'no-repeat, no-repeat, no-repeat', backgroundBlendMode: 'multiply',}}>
      <Box sx={{
         width: '100%',
         height: 'flex',
         display: 'flex',
         backgroundColor: "rgba(0,0,0,0.5)",
 	 position: 'fixed', top:'0px', left: '0px', 
      }}>
         <Box 
            component="img"
            sx={{height:'50px',alignItems:'center',justifyContent:'center',display:'flex',top:'0px',left:'0px',}}
            src={`${process.env.PUBLIC_URL}/exalabs-logo.png`}
         />
         <Typography sx={{ margin: '15px', fontFamily: "'DM Mono', monospace", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.16em', textTransform: 'uppercase', color: '#FFF', borderLeft: '50px solid rgba(0,0,0,0)', position: 'fixed', top:'0px',  }}> Exalabs UMass Lowell </Typography>
      </Box>
      <Box sx={{borderRadius: '10px', display: 'flex', flexDirection: 'column',  width: '50%', height: '80%', border: '2px solid #001000', margin: '10% 0 0 0', }}>
        <DemographicsForm errors={errors} countries={countries} professions={professions}/>
        <Button sx={{ margin: '48px 0 0', backgroundColor: "#FFF", fontWeight: 300, fontSize: '15px', letterSpacing: '0.15em', textTransform: 'uppercase', color: '#9a9690', border: '1px solid rgba(26,25,23,0.2)', borderRadius: '4px', padding: '10px 28px', '&:hover': { color: '#1a1917', borderColor: '#2a2a8c', backgroundColor: 'transparent' }, }} variant="contained" onClick={() => {
           // goes to the next screen for getting user demographics
           if (validate()) {
              setDemographics(false);
              setInitSurvey(true);
              setTitleFloat(true);
           }
        }}>
                 <Typography sx={{ fontSize: 20, fontFamily: "'Cormorant Garamond', Georgia, serif"}}> <strong>Submit</strong> </Typography>
        </Button>
      </Box>   
      </div>
    );
  }
  if (loading) return <div style={{ padding: 20 }}>Loading videos…</div>;
  if (ended) {
    rankedVideos = {};
    selectionTimes = {};
    notSelectionTimes = {};
    rankings.forEach((video, index) => {
      rankedVideos[video.id+'NAME:'+video.name] = index;
    });
    times.forEach((time, index) => {
        selectionTimes[time] = chosenVids[index];
        console.log("selected "+selectionTimes[time]);
    });
    times.forEach((time, index) => {
        notSelectionTimes[time] = notChosenVids[index];
        console.log("not selected "+notSelectionTimes[time]);
    });
    
    return (
      //background: `linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.45)), radial-gradient(circle at center, rgba(0,0,204,0.6) 50%, rgba(179,217,255, 0.6) 100%), url('general-white-blue.jpg')`
      <>
      <div style={{ justifyContent: 'center', alignItems: 'center', flexDirection: 'column', display: 'flex', width: '100%', minHeight: '100vh', overflowX: 'hidden', background: `url('general-white-blue.jpg')`, transition: 'background-image 0.5s ease', backgroundSize: '100% 100%, 100% 100%, contain', backgroundPosition: 'center, center, center', backgroundRepeat: 'no-repeat, no-repeat, no-repeat', backgroundBlendMode: 'multiply',}}>
      <Box sx={{
         width: '100%',
         height: 'flex',
         display: 'flex',
         backgroundColor: "rgba(0,0,0,0.5)",
 	 position: 'fixed', top:'0px', 
      }}>
         <Box 
            component="img"
            sx={{height:'50px',alignItems:'center',justifyContent:'center',display:'flex',top:'0px',left:'0px',}}
            src={`${process.env.PUBLIC_URL}/exalabs-logo.png`}
         />
         <Typography sx={{ margin: '12px 0 12px 10px', fontFamily: "'DM Mono', monospace", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.16em', textTransform: 'uppercase', color: '#FFFFFF', borderLeft: '1px solid rgba(26,25,23,0.15)', paddingLeft: '10px', }}> Exalabs UMass Lowell </Typography>
      </Box>
        <Box sx={{ justifyContent: 'center', alignItems: 'center', position: 'relative', opacity: titleFloat ? 1 : 0, transform: titleFloat ? "translateY(0)" : "translateY(-50px)", transition: "opacity 1s ease-out, transform 1s ease-out", }}>
           <Typography sx={{fontWeight: 'bold', fontSize: '50px', fontFamily: "'Cormorant Garamond', Georgia, serif", alignItems: 'center', justifyContent: 'center', display: 'flex', position: 'relative', margin: '50px', color: '#000',}}>
		Survey complete
	   </Typography>
           <Typography sx={{fontWeight: '', fontSize: '35px', fontFamily: "'Cormorant Garamond', Georgia, serif", alignItems: 'center', justifyContent: 'center', display: 'flex', position: 'relative', margin: '30px', color: '#000',}}>
		
	   </Typography>
        </Box>

        <EmailBox xpos='0%' ypos='20%' userIP={userIPAddress}/>
<Button sx= {{ gap: '50px', margin: '50px 0', borderBottom: '100px', color: '#000', border: '1px solid #000', '&:hover': { backgroundColor: 'rgba(150, 220, 255, 0.9)', color: '#FFF', border: '1px solid #000',}, fontSize: '25px', }} onClick={restart}>Restart</Button>
        <Box>
           <Typography sx={{fontWeight: '', fontSize: '20px', fontFamily: "'Cormorant Garamond', Georgia, serif", alignItems: 'center', justifyContent: 'center', display: 'flex', position: 'relative', margin: '30px', color: '#000',}}>
		To learn more, click on
                <a href={`${process.env.PUBLIC_URL}/info.html`} rel="noopener noreferrer"  style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", color: '#31F5A7', }}>this link</a>!
	   </Typography>
        </Box>
        
       </div>
      </>
    );
  }

/*
        */

  if (!pair || pair.length < 2) {
    return (
      <div style={{ padding: 20 }}>
      <Box sx={{
         width: '100%',
         height: 'flex',
         display: 'flex',
         backgroundColor: "rgba(0,0,0,0.5)",
 	 position: 'fixed', top:'0px', 
      }}>
         <Box 
            component="img"
            sx={{height:'50px',alignItems:'center',justifyContent:'center',display:'flex',top:'0px',left:'0px',}}
            src={`${process.env.PUBLIC_URL}/exalabs-logo.png`}
         />
         <Typography sx={{ margin: '10px', fontFamily: "'DM Mono', monospace", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.16em', textTransform: 'uppercase', color: '#FFF', borderLeft: '50px solid rgba(0,0,0,0)', }}> Exalabs UMass Lowell </Typography>
      </Box>
        <h2>Not enough videos to compare</h2>
        <Button sx= {{ gap: '150px', margin: '100px 0'}}  onClick={restart}>Reload</Button>
      </div>
    );
  }
  
  return (
    <div style={{ justifyContent: 'center', flexDirection: 'column', display: 'flex', width: '100%', minHeight: '100vh', overflowX: 'hidden', background: '#f5f3ef', transition: 'background-color 0.5s ease', }}>
    <div style={{ fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial", alignItems: 'stretch', }}>
      <div>
      <Box sx={{
         width: '100%',
         height: 'flex',
         display: 'flex',
         backgroundColor: "rgba(0,0,0,0.5)",
         position: 'fixed',top:'0px',
         zIndex: 100,
         padding: '0 24px',
      }}>
         <Box 
            component="img"
            sx={{height:'50px',alignItems:'center',justifyContent:'center',display:'flex', position: 'fixed',top:'0px',left:'0px',}}
            src={`${process.env.PUBLIC_URL}/exalabs-logo.png`}
         />
         <Typography sx={{ margin: '13px', fontFamily: "'DM Mono', monospace", fontWeight: 'bold', fontSize: '15px', letterSpacing: '0.16em', textTransform: 'uppercase', color: '#FFF', borderLeft: '20px solid rgba(0,0,0,0)', }}> Exalabs UMass Lowell </Typography>
      </Box>   
      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 25, padding: '60px', color: '#000' }}>
        <span style={{ fontFamily: "'Cormorant Garamond', Georgia, serif" }}>Click the video you think is{' '}</span>&nbsp;
        <span style={{ fontFamily: "'Cormorant Garamond', Georgia, serif" }}><strong>more complex</strong></span>&nbsp;
      </Box>
      
      <div style={{ display: "flex", gap: 12, alignItems: "stretch" }}>
        <VideoCard item={pair[0]} reloadKey={reloadKey} setReloadKey={setReloadKey} onChoose={() => onChoose("left")} position="left" fadeAnimation={visible} />
        <VideoCard item={pair[1]} reloadKey={reloadKey} setReloadKey={setReloadKey} onChoose={() => onChoose("right")} position="right" fadeAnimation={visible} />
      </div>
      <div style={{ padding: '20px 24px 32px', maxWidth: '900px', margin: '0 auto', width: '100%'}}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: 'center',  marginBottom: '10px',}}>
           <Typography sx={{fontSize: 22, fontFamily: "'Cormorant Garamond', Georgia, serif"}}>PROGRESS</Typography>
	   <div style={{ display: "flex", alignItems: 'center', gap: '10px',}}>
              <Typography sx={{fontSize: 30, fontWeight: 'bold', fontFamily: "'Cormorant Garamond', Georgia, serif"}}>{vidnum - 1}</Typography>/<Typography sx={{fontSize: 22, fontFamily: "'Cormorant Garamond', Georgia, serif"}}>{numVideos} pairs complete</Typography>
           </div>
        </div>
        <div style={{ display: "flex", justifyContent: "center", }} >
           <ProgressBar number={vidnum-1} total={numVideos} />
        </div>
      </div>   

      </div>
      
    </div>
    </div>
  );
}

const count = (ms) => {
  const minutes = Math.floor(ms / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  const milliseconds = Math.floor(ms % 1000);
  return (
    String(minutes).padStart(2, "0") + ":" +
    String(seconds).padStart(2, "0") + ":" +
    String(milliseconds).padStart(3, "0")
  );
};

function Timerbox({ start, time_to_choose }) {
  const [timer, setTimer] = useState(0);  
  useEffect(() => {
    const interval = setInterval(() => {
      setTimer(performance.now() - start);
    }, 16);
    return () => clearInterval(interval);
  }, [start]);
  return (
    <div style={{ width: '200px', height: '200px', borderRadius: '200px', backgroundColor: "#CCFFFF", justifyContent: 'center', alignItems: 'center', display: 'flex', }}>
      <div style={{ width: '180px', height: '180px', borderRadius: '180px', backgroundColor: "#4D4DFF", position: 'relative', justifyContent: 'center', alignItems: 'center', display: 'flex', }}>
        <div style={{ width: '170px', height: '170px', borderRadius: '170px', backgroundColor: "#CCFFFF", justifyContent: 'center', alignItems: 'center', display: 'flex', }}>
          <Typography sx={{ alignItems: 'center', fontWeight: 'bold', fontFamily: "'Orbitron', monospace", fontSize: '1.5rem', textShadow: `0 0 5px rgba(0,0,255,0.6), 0 0 10px rgba(0,0,255,0.4)`}}>{ count(timer, time_to_choose) }</Typography>
        </div>
      </div>
    </div>
  );
} 

function ProgressBar({ number, total }) {
    return (
    <Box sx={{ display: 'flex', width:'100%', height:24, display:'flex', borderRadius: '5px', position: 'relative',  overflow: 'hidden' }}>
      <Box sx={{backgroundColor: '#31F5A7', width: `${(number/(total))*100}%`}}>
      </Box>
      <Box sx={{backgroundColor: '#778385', width: `${100 - (number/(total))*100}%`}}/>
      <Typography sx={{position: 'absolute', top: '50%', left:'50%', transform:'translate(-50%, -50%)',}}><strong>{Math.round((number/(total))*100)}%</strong></Typography>
    </Box>
    );
}

function VideoCard({ item, onChoose, position = "left", fadeAnimation, reloadKey, setReloadKey }) {
  const observerRef = useRef();
 
useEffect(() => {
  const observer = new IntersectionObserver(
    (entries) => {
      // When the element enters the viewport, update the key
      if (entries[0].isIntersecting) {
        setReloadKey(Date.now());
      }
    },
    { threshold: 0.1 } // Triggers when 10% of the element is visible
  );

  const currentElement = observerRef.current;
  if (currentElement) {
    observer.observe(currentElement);
  }

  return () => {
    if (currentElement) {
      observer.unobserve(currentElement);
    }
  };
}, []);

  if (!item) return null;
  return (
    <Box
      onClick={onChoose}
      role="button"
      tabIndex={0}
      sx={{
        cursor: "pointer",
        width: '100%',
        border: "1.5px solid rgba(26,25,23,0.1)",
        borderRadius: 8,
        padding: '20px',
	margin: position === "left" ? '0 2% 0 16%' : '0 16% 0 2%',
        boxSizing: "border-box",
        backgroundColor: '#ffffff',
        '&:hover': { boxShadow: '0px 0px 40px #54A6F0' },
        '&:active': { transform: 'translateY(0px) scale(0.995)' },
        opacity: fadeAnimation ? 1 : 0,
        transform: fadeAnimation ? "translateX(0)" : position === "left" ? "translateX(-30px)" : "translateX(30px)",
        transition: "opacity 1s ease-out, transform 1s ease-out",
      }}
      onKeyDown={(e) => { if (e.key === "Enter") onChoose(); }}
    >
      <div style={{ marginBottom: '8px', fontFamily: "'DM Mono', monospace", fontWeight: 300, color: '#000', letterSpacing: '0.2em' }}>
        
      </div>
      {item.url && (
        <div ref={observerRef} style={{ lineHeight: 0, borderRadius: '2px', overflow: 'hidden', aspectRatio: '1', }}>
          <img
            src={`${process.env.PUBLIC_URL + item.url.replace("/netlogo-video-sorter", "").replace(/\.gif$/i, ".gif")}?cb=${reloadKey}`}
            style={{ width: "100%", height: "100%", objectFit: "cover", display: 'block' }}
          />
        </div>
      )}
    </Box>
  );
}

// -----Expandable videocard-------
interface ExpandMoreProps extends IconButtonProps {
  expand: boolean;
}

const ExpandMore = styled((props: ExpandMoreProps) => {
  const { expand, ...other } = props;
  return <IconButton {...other} />;
})(({ theme }) => ({
  marginLeft: 'auto',
  transition: 'transform 0.3s ease-in-out',
  variants: [
    {
      props: ({ expand }) => !expand,
      style: {
        transform: 'rotate(0deg)',
      },
    },
    {
      props: ({ expand }) => !!expand,
      style: {
        transform: 'rotate(180deg)',
      },
    },
  ],
}));


function RankCard({ item, index, position = "left" }) {
  const [expanded, setExpanded] = useState(false);
  const [url,name] = item.split("NAME:");
  
  const handleExpandClick = () => {
    setExpanded(!expanded);
  };

  if (!item) return null;
  return (
    <div
      role="button"
      tabIndex={0}
      style={{
        cursor: "pointer",
        maxWidth: "900px",
        width: "100%",
        border: "1px solid #0055FF",
        borderLeft: "6px solid #0055FF", // ← accent bar
        borderRight: "6px solid #0055FF", // ← accent bar
        borderRadius: 8,
        padding: '8px',
        boxSizing: "border-box",
        backgroundColor: 'rgba(179, 217, 255, 0.67)',
      }}
      onKeyDown={(e) => {
        if (e.key === "Enter") onExpand();
      }}
    >
    <Box>
    <Box sx={{ display: 'flex', alignItems: 'center',}}>
      <div style={{
          width: '200px',
          height: '100px',
          flexDirection: 'horizontal',
          backgroundColor: "#f0f4ff",
          display: 'flex',
          alignItems: "center",
          justifyContent: "center",
          padding: '6px 30px',
          fontSize: '20px',
          fontWeight: 700,
          color: "#3f51b5",
          borderRadius: '50px',
          borderLeft: "1px solid #ddd",
        }}> 
        {index}
      </div>
      <Box sx={{
      flex: 1,
      width: '500px',
      fontSize: '1.7rem',
      fontWeight: 600,
      textAlign: 'left',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      }}>
        {name}
      </Box>
      <Box sx={{ display: 'flex', justifyContent: 'flex-end', alignItems:'center',  }}>
    
        <ExpandMore
          expand={expanded}
          onClick={handleExpandClick}
          aria-expanded={expanded}
          aria-label="show parameters"
          title="Toggle Parameters"
          sx={{ ml: 1,}} // Add margin for spacing
        >
          <ExpandMoreIcon sx={{ flex: 1, width: 'flex' }} />
        </ExpandMore>
      </Box>
      </Box>

      <Collapse in={expanded} timeout={100} unmountOnExit>
      <Box sx={{ 
            pt: 1, 
            mt: 1, 
            pl: '115px', // Aligns description text with video name
            borderTop: '1px solid #eee', 
            width: 'flex', 
            backgroundColor: '#f9f9f9',
            borderRadius: '0 0 8px 8px',
            pr: 1, pb: 1 
        }}>
        <Typography
          variant="body2"
          sx={{ color: 'text.secondary', whiteSpace: 'pre-line' }}>
          <strong style={{ color: '#007bff' }}><strong>URL:</strong><p>{url}</p></strong>
        </Typography>
      <img
        src={process.env.PUBLIC_URL+'/'+url}
        controls
        style={{ width: 'flex', height: "320px", borderRadius: 2 }}
      />
      </Box>
      </Collapse>
    </Box>


      <div style={{ marginTop: 8, fontSize: 12, color: "#666" }}>{item.id}</div>
    </div>
  );
}


function startBoard({ children }) {
      <Box sx={{ 
            pt: 1, 
            mt: 1, 
            pl: '115px', // Aligns description text with video name
            borderTop: '1px solid #eee', 
            width: '100%', 
            backgroundColor: '#0044CC',
            borderRadius: '10%',
            pr: 1, pb: 1 
        }}>
         {children}
      </Box>
}
// startBoard <-- instructionCard <-- presurvey_messages
// instructionboard <-- instructionCard <-- presurvey_messages

const start_messages = [{ type: "instruction", textBefore: `Hello!\nWelcome to the swarm complexity ranking survey!\nClick `, bold: "Next Page", textAfter: " to start the survey."}];
const presurvey_messages = [{type: "instruction", textBefore: "", bold: `GOAL OF THE STUDY:\n\n`, textAfter: `This survey aims to determine the relative complexity of swarms based on which videos you select as more complex in a series of pairwise comparisons.\n`}, "You will be presented with a series of videos that you will be asked to rank according to complexity.",
		"A series of pairs of videos will be displayed, where one video is more complex than the other. Your task is to select which you think is the most complex.",
                "We will show you a sample pair now."];

const final_message = [{ type: "instruction", textBefore: "Click the ", bold: "START", textAfter: ` button to begin the survey once you have read and understood these instructions.\n\n Have fun!`}];


function InstructionCard({ psg, textSize }) {

   const newlinerender = (text) => 
      text.split('\n').map((line, i, arr) => (
          <span key={i}>
              {line}
              {i < arr.length - 1 && <br />}
          </span>
      ));
   if (typeof psg === "string") {
      return (
         <div style={{ 
           width: '400px', 
           height: '300px', 
           borderRadius: '10px', 
           borderColor: '#3399FF', 
           backgroundColor: 'white', 
           color: '#003366', 
           padding: '150px 20px',
	   whiteSpace: 'pre-wrap',
           fontSize: textSize,
         }}>
           {psg}
         </div>
      );
   }
   if (psg.type === "instruction") {
      return (
         <div style={{ 
            width: '500px',
            alignCenter: 'center',
            justifyContent: 'center', 
            height: 'flex', 
            borderRadius: '10px', 
            margin: '20px', 
            borderColor: '#3399FF', 
            backgroundColor: 'white', 
            color: '#003366', 
            padding: '150px 20px',
            fontSize: textSize
         }}>
            {newlinerender(psg.textBefore)}
            <strong>{newlinerender(psg.bold)}</strong>
            {newlinerender(psg.textAfter)}
         </div>
      );
   }
} 

function InstructionBoard({ msgs, nextLink, setNextLink, currLink, setCurrLink, nextText, textSize }) {
   const [currentInstruction, setCurrentInstruction] = useState(0);
   const next = () => {
      setCurrentInstruction(curr => (curr + 1));
   };
   const prev = () => {
      setCurrentInstruction(curr => (curr - 1));
   };
   return (
      <div style={{ width: '1000px',
                   borderRadius: '50px',
                   padding: '16px 20px',
                   lineHeight: '1.5',
                   background: '#FFF',
                   display: 'flex',
                   flexDirection: 'column', 
                   gap: '20px', 
                   marginTop: '5%',
                   textAlign: 'center',
                   alignItems: 'center', 
                   justifyContent: 'center', }}>
         <Typography 
           variant="h4"
           sx={{
             fontFamily: "'Cormorant Garamond', Georgia, serif",
             fontWeight: 600,
             letterSpacing: '0.18em',
             textTransform: 'uppercase',
             color: '#003366',
             fontWeight: 'bold',
           }}> 
             Instructions 
         </Typography>
         <Fade in timeout={300} key={currentInstruction}>
         <p>< InstructionCard psg={msgs[currentInstruction]} textSize={textSize} /></p>
         </Fade>
         <Box sx={{
	      height: '50%', 
	      alignItems: 'center', 
	      gap: '5%',
	      position: 'relative', }}>
           {msgs.length > 1 && currentInstruction > 0 && 
               (<Button onClick={prev} sx={{ backgroundColor: '#80D4FF', color: '#000000', '&:hover': { backgroundColor: '#0066FF', color: '#FFFFFF', textSize: textSize} }} >
		   <Typography sx={{ textSize: textSize}}>Previous</Typography>
                </Button>)
           }
           { msgs.length > 1 && <Typography sx={{ gap: '20px', fontWeight: 'bold', fontFamily: `'Orbitron', 'Roboto Mono', 'JetBrains Mono', monospace`, }}>
              {(currentInstruction+1)}/{msgs.length}
           </Typography> }
           {msgs.length > 1 && currentInstruction < msgs.length - 1 && (
		<Button onClick={next} sx={{ backgroundColor: '#80D4FF', color: '#000000', '&:hover': { backgroundColor: '#0066FF', color: '#FFFFFF'} }} >
		   <Typography sx={{ textSize: textSize }}>Next</Typography>
	        </Button>)
	   }
           {currentInstruction >= msgs.length - 1 && !nextLink && (
		<Button onClick={() => {setNextLink(true); console.log("next link is ", nextLink); setCurrLink(false);}} sx={{ backgroundColor: '#80D4FF', color: '#000000', '&:hover': { backgroundColor: '#0066FF', color: '#FFFFFF'} }} >
		   <Typography sx={{ textSize: textSize}}>{nextText}</Typography>
	        </Button>)
	   }
         </Box>
      </div>
   );
}

function ChoiceCard({ chosen, notChosen, time }) {
   return (
    <Box>
    <Box sx={{
       display:'flex', 
       justifyContent:'center',
       alignItems: 'center',
    }}>
     <Box sx={{
        borderColor:'#006699',
        background:'rgba(179, 217, 255, 0.67)',
        border:'10px solid #006699',
        borderRadius: '5px',
        justifyContent:'center',
        alignItems: 'center',
        display:'flex',
        flexDirection: 'column',
     }}>
       <Typography sx={{
         fontFamily: `'Orbitron', 'Roboto Mono', 'JetBrains Mono', monospace`,
         fontWeight: 600,
         letterSpacing: '0.12em',
         textTransform: 'uppercase', 
         alignItems:'center',        
       }}>
        Chosen:
       </Typography>
       <Typography sx={{ padding:'15px', }}>
        {chosen}
       </Typography>
     </Box>
     <Box sx={{
        borderColor:'#006699',
        background:'rgba(179, 217, 255, 0.67)',
        border:'10px solid #006699',
        borderRadius: '5px',
        justifyContent:'center',
        alignItems: 'center',
        display:'flex',
        flexDirection: 'column',
     }}>
       <Typography sx={{
         fontFamily: `'Orbitron', 'Roboto Mono', 'JetBrains Mono', monospace`,
         fontWeight: 600,
         borderRadius: '5px',
         letterSpacing: '0.12em',
         textTransform: 'uppercase',  
         alignItems:'center',               
       }}>
        Not chosen:
       </Typography>
       <Typography sx={{ padding:'15px', borderRadius: '5px',}}>
        {notChosen}
       </Typography>
     </Box>
    </Box>
     <Box sx={{
        borderColor:'#006699',
        background:'rgba(179, 217, 255, 0.67)',
        borderRadius: '5px',
        border:'5px solid #006699',
	gap:'10px',
        justifyContent:'center',
        alignItems: 'center',
        display:'flex',
        flexDirection:'row',
     }}>
       <Typography sx={{ padding:'15px 0px', borderRadius: '5px', }}>
        Time to choose:
       {time} seconds
       </Typography>
     </Box>
    </Box>
   );
}


function HelpBox({ headline, msg, xpos, ypos }) {
   return (
      <Box sx={{      
          position: 'absolute',
          justifyContent: 'center',
          top: ypos,
          left: xpos,
          transform: 'translate(-${xpos}, -${ypos})', 
          height: 'flex',
          padding: '20px 20px',
          zIndex: 1300,
          backgroundColor: '#99CCFF',
          border: '10px solid #001580',
          borderRadius: '5px',
          alignItems: 'center',
          display: 'flex',
          flexDirection: 'column',
          textAlign: 'center',  
      }}>
         <h2><strong>{headline}</strong></h2>
         <p><Typography sx={{ fontSize: '20px' }}>{msg}</Typography></p>
      </Box>
   );
}


const parseParams = (filename) => {
    console.log("in parseparams");
    const params = [];
    const part_to_parse = filename.split("/").pop() || filename;  // get last part of filename
    const is_gif = filename.includes(".GIF"); // is file .gif?
    let param_names = part_to_parse.split(".GIF");
    param_names = param_names[0].split("_"); // get params and values
    console.log("param names are: ", param_names);
    const date = param_names[0];
    const param_parts = param_names; // is_gif ? param_names.slice(1) : param_names; // split by parameters if the file is a gif
    console.log(param_parts);
    param_parts.forEach((part) => {
        const match = part.match(/^([a-zA-Z]+)=([0-9.]+)$/);
        if (match) {
            const [, paramtype, paramval] = match;
            params.push(`${paramtype}:${parseFloat(paramval)}`);
            console.log(`${paramtype}:${parseFloat(paramval)}`);
        }
    });
    console.log("in function: "+params);
    return [date, params];
}

const getFile = (userIP) => {
    // 1. Define CSV headers

    let date = new Date();
    let formattedDate = `${date.getFullYear()}-${('0' + (date.getMonth() + 1)).slice(-2)}-${('0' + date.getDate()).slice(-2)}-${date.getHours()}:${('0' + date.getMinutes()).slice(-2)}:${('0' + date.getSeconds()).slice(-2)}`;
    console.log(formattedDate);

    // 2. Map items to CSV rows
    // a) Mapping the video rankings to the CSV rows
    const csvRows = Object.entries(rankedVideos).map((rankedVid, index) => {
      // Parse parameters again to include their values in the CSV
      console.log("ranked: "+rankedVid);
      let rankedVidParts = rankedVid[0].split("NAME:");

      const [url, name] = rankedVidParts;
      console.log("url: "+url);
      console.log("name: "+name);
      console.log("index: "+index);

      let [date, params] = parseParams(url);
      console.log("params: "+params);
 
      // parameter values for each video
      //const paramValues = Object.entries(params).map(p => params[p] !== undefined ? params[p] : 'N/A');
      let paramValues = [];
      params.forEach(p => { 
          //console.log("param: "+p);
          paramValues.push(p.split(":")[1]);
      });

      let demoColumns = ["", "", "", "", ""];
      if (index === 0) demoColumns = ["", "Level of Education", demographicsData["highestDegree"]];
      if (index === 1) demoColumns = ["", "Number of Languages", demographicsData["numLanguages"]];
      if (index === 2) demoColumns = ["", "Hobbies", demographicsData["hobbies"]];
      if (index === 3) demoColumns = ["", "Profession", demographicsData["profession"]];
      
      return [
        index+1, // Current Rank
        url, 
        ...paramValues, 
        ...demoColumns
      ].join(',');

    });
    const headers = [
      "Rank", 
      "Name", 
      "vision",
      "min separation",
      "max alignment turn",
      "max coherence turn",
      "max separation turn",
      "population",
      "",
      "Age", demographicsData["age"], 
      "",
      userIP
    ];
    console.log("csvrows: "+csvRows);
    const content = [
      headers.join(','),
      ...csvRows,
    ];  //.join('\n');

    // b) Mapping the video selections to the CSV rows
    console.log("selectionTimes:", JSON.stringify(selectionTimes));
    const choices = Object.entries(selectionTimes).map((selectionTime, index) => {
      // Parse parameters again to include their values in the CSV
      console.log("selectionTime: "+selectionTime);
      let [time, name] = selectionTime;

      console.log("name: "+name);
      console.log("time: "+time);
      console.log("index: "+index);

      let [date, params] = parseParams(name);

      let paramValues = [];
      params.forEach(p => { 
          //console.log("param: "+p);
          paramValues.push(p.split(":")[1]);
      });
      console.log([
        time, // Current time
        name, 
        notSelectionTimes[time],
      ]);
      return [
        time, // Current time
        name, 
        notSelectionTimes[time],
      ].join(',');
      
    });
    const new_headers = [
      "Time", 
      "Chosen", 
      "Not chosen"
    ];
    console.log("choices: "+choices);


    const new_content = [
      'Ranked videos, , , , , , , , ,Demographics, , ,IP Address',
      ...content,
      '',
      '',
      'Choice selections',
      new_headers.join(','),
      ...choices

    ].join('\n');
    let resultsContent = new_content;
    let resultsFile = 'video_complexity_order-'+formattedDate+'.csv';
    return [resultsFile, resultsContent];
} 

const downloadOrderAsCSV = () => {
    let [resultsFile, resultsContent] = getFile();
    // 3. Create a Blob and download link
    const blob = new Blob([resultsContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);

    // 4. Trigger download
    const link = document.createElement('a');
    link.href = url;
   
    // get date
    link.setAttribute('download', resultsFile);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url); 
};


// button to email results
function EmailBox({ xpos, ypos, userIP }) {
  const [open, setOpen] = React.useState(false);

  async function renderEmail() {
    /*try {
      let [resultsFile, resultsContent] = getFile();
      const file = new File([resultsContent], resultsFile, { type: "text/csv" });

      const formData = new FormData();
      formData.append("file", file);

      const res = await fetch("https://swarm-backend-ga0y.onrender.com/send-email", {
        method: "POST",
        body: formData
      });

      const text = await res.text();
      console.log(text);

      setOpen(true); // open popup
    } catch (err) {
      console.error(err);
      alert("Error sending email " + err);
    }*/

  let [resultsFile, resultsContent] = getFile(userIP);
  const file = new File([resultsContent], resultsFile, { type: "text/csv" });
  // sending the information from the survey in the expected format
  const formData = new FormData();
  formData.append("to", "Sriram_Krishnamoorthy@student.uml.edu");
  formData.append("subject", "Swarm Ranking Survey Results");
  formData.append("text", "Please find attached CSV results");
  formData.append("file", file);
  console.log("Sending ", file);
  fetch("https://swarm-backend-ga0y.onrender.com/send-email", {
    method: "POST",
    body: formData
  })
.then(async (res) => {
  const text = await res.text();
  console.log("Server response:", text);

  if (!res.ok) {
    throw new Error(text);
  }

  alert("Submission complete!"); // once the authentication and drive connection works
})
    .catch((err) => {
      console.error(err);
      alert("Error sending email"+err);
    });


  }


  return (
    <>
      <Box sx={{ position: "relative", display: "inline-block", top: "20%" }}>
        <Button
          sx={{
            width: "100%",
            margin: "5px",
            borderRadius: "5px",
            backgroundColor: "rgba(128, 207, 255, 0.5)",
            padding: "20px",
            color: "#0022CC"
          }}
          onClick={renderEmail}
        >
          <Typography sx={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontWeight: "bold", fontSize: "30px" }}>
            Submit
          </Typography>
        </Button>
      </Box>

      <Dialog open={open} onClose={() => setOpen(false)}>
        <DialogContent>
          <Typography><strong>Submission complete</strong></Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpen(false)}>OK</Button>
        </DialogActions>
      </Dialog>
    </>
  );
}

// sending the email to the receiver (my email)
const sendEmail = () => {  
    let [resultsFile, resultsContent] = getFile();
    console.log(resultsContent);
    resultsContent = resultsContent.replace(/,/g, '\t|');
const attachments = [
  {
    name: resultsFile,               // filename
    data: resultsContent,                   // base64 string (no prefix)
    type: 'text/csv'                   // MIME type
  }
];
console.log("Sending "+resultsFile);

/*emailjs.send('service_oua0645', 'template_0sn1aba', {
  name: 'Sriram',
  email: 'sriramk1000@gmail.com',
  message: 'Please find attached CSV results:\n'+resultsContent,
}, '79TzH81kp9RcNqdrX')
.then(response => {
  console.log('Email sent successfully!', response.status, response.text);
})
.catch(err => {
  console.error('Failed to send email.', err);
});*/


// fetch the request to the render backend service for the survey
fetch('https://swarm-backend-ga0y.onrender.com/send-email', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    to: recipientEmail,
    subject: 'Swarm Ranking Survey Results',
    text: 'Please find your results:\n' + resultsContent,
    html: `<p>Please find your results:</p><pre>${resultsContent}</pre>`,
  }),
})
.then(res => res.json())
.then(data => {
  if (data.success) console.log('Email sent!', data.messageId);
  else console.error('Failed:', data.error);
})
.catch(err => console.error('Request failed:', err));

};

// drafts the email with the survey results file and attaches to the POST request to be sent to the Render backend
function renderEmail() {
  let [resultsFile, resultsContent] = getFile();
  const file = new File([resultsContent], resultsFile, { type: "text/csv" });
  // sending the information from the survey in the expected format
  const formData = new FormData();
  formData.append("to", recipientEmail);
  formData.append("subject", "Swarm Ranking Survey Results");
  formData.append("text", "Please find attached CSV results");
  formData.append("file", file);
  console.log("Sending ", file);
  fetch("https://swarm-backend-ga0y.onrender.com/send-email", {
    method: "POST",
    body: formData
  })
.then(async (res) => { // waits for response to from the Render service, then notifies submission success
  const text = await res.text();
  console.log("Server response:", text);

  if (!res.ok) {
    throw new Error(text);
  }
  // If fails, or dialog box says "Error sending email, not authenticated", enter in search bar https://swarm-backend-ga0y.onrender.com/auth
  alert("Submission complete!");
})
    .catch((err) => {
      console.error(err);
      alert("Error sending email"+err);
    });

}


/* DEMOGRAPHICS */
function DemographicsForm({ errors, countries, professions }) {
    const [age, setAge] = useState("");
    const [highestDegree, setHighestDegree] = useState("");
    const [numLanguages, setNumLanguages] = useState("");
    const [hobbies, setHobbies] = useState("");
    const [profession, setProfession] = useState("");
    const ages = ["18 - 22 years", "23 - 27 years", "28 - 32 years",  "33 - 37 years", "38 - 42 years", "43 - 47 years"];
    const degrees = ["High School Diploma", "Bachelor's", "Graduate/Master's", "Ph.D/Doctorate"];
   
    const handleHobbiesChange = (e) => {
       setHobbies(e.target.value);
       demographicsData["hobbies"] = e.target.value;
       console.log("New hobbies: "+demographicsData["hobbies"]);
    };

    const handleNumLanguagesChange = (e) => {
       setNumLanguages(e.target.value);
       demographicsData["numLanguages"] = e.target.value;
       console.log("number of languages: "+demographicsData["numLanguages"]);
    };

    const handleProfessionChange = (selectedList) => {
       setProfession(selectedList);
       demographicsData["profession"] = selectedList.join(",");
       console.log("New profession: "+demographicsData["profession"]);
    };

    const handleProfessionSearch = (value) => {
       setProfession(value);
       if (!professions.includes(value) && value.trim() !== "") {
          demographicsData["profession"] = value; 
          console.log("New profession: "+demographicsData["profession"]);
       }
    };

    return (
       <Box sx={{display: 'flex', flexDirection: 'column', justifyContent: 'left', marginLeft: '5%', }}>
           <Box sx={{ display: 'flex', flexDirection: 'column', marginBottom: 2 }}>
               <Typography sx={{  }}> Please select which age range applies to you: </Typography>
                   <Select value={age} required onChange={(e) => {
                          setAge(e.target.value);
                          demographicsData["age"] = e.target.value; 
                          console.log("demographics data: ", demographicsData["age"]);
                       }} displayEmpty>
                       {ages.map((a) => (
                           <MenuItem key={a} value={a}>
                                {a}
                           </MenuItem>
                       ))}
                   </Select>
                   {errors.age && <Typography color="error" variant="caption">{errors.age}</Typography>}
           </Box>
           <Box sx={{ display: 'flex', flexDirection: 'column', marginBottom: 2 }}>
               <Typography sx={{  }}> Please select the highest certification you received: </Typography>
                   <Select value={highestDegree} required onChange={(e) => {
                          setHighestDegree(e.target.value);
                          demographicsData["highestDegree"] = e.target.value; 
                          console.log("demographics data: ", demographicsData["highestDegree"]);
                       }} displayEmpty>
                       {degrees.map((s) => (
                           <MenuItem  key={s} value={s}>
                                {s}
                           </MenuItem>
                       ))}
                   </Select>
                   {errors.highestDegree && <Typography color="error" variant="caption">{errors.highestDegree}</Typography>}
           </Box>
           <Box sx={{ display: 'flex', flexDirection: 'column', marginBottom: 2 }}>
               <Typography sx={{  }}> How many languages do you speak? </Typography>
                   <Box sx={{borderRadius: 1, border: '1px solid #D4D0CF'}}>

                   <TextField
                   sx={{ width: '100%', }}
                   onChange={handleNumLanguagesChange} // Function will trigger on change event
                   displayValue="Enter number of languages spoken" // Property name to display in the dropdown options
                   />            

                   </Box>
                   {errors.numLanguages && <Typography color="error" variant="caption">{errors.numLanguages}</Typography>}
           </Box>
           <Box sx={{ display: 'flex', flexDirection: 'column', marginBottom: 2 }}>
               <Typography sx={{  }}> What are your hobbies? </Typography>
                   <Box sx={{borderRadius: 1, border: '1px solid #D4D0CF'}}>

                   <TextField
                   sx={{ width: '100%', }}
                   onChange={handleHobbiesChange} // Function will trigger on change event
                   displayValue="Enter hobbies" // Property name to display in the dropdown options
                   />                   
                   
                   </Box>
                   {errors.hobbies && <Typography color="error" variant="caption">{errors.hobbies}</Typography>}
           </Box>
           <Box sx={{ display: 'flex', flexDirection: 'column', marginBottom: 2 }}>
               <Typography sx={{  }}> What best describes your profession? </Typography>
                   <Box sx={{borderRadius: 1, border: '1px solid #D4D0CF'}}>

                   <Multiselect
                   options={professions} // Options to display in the dropdown
                   singleSelect={false}
                   isObject={false}
                   selectedValues={profession} // Preselected value to persist in dropdown
                   onSelect={handleProfessionChange} // Function will trigger on select event
                   onRemove={handleProfessionChange} // Function will trigger on remove event
                   onSearch={handleProfessionSearch}
                   displayValue="Enter and select profession" // Property name to display in the dropdown options
                   onBlur={() => {
                       if (professionInput && !professions.includes(professionInput)) {
                       // Turn their raw string text into an array layout so chips render correctly
                           setProfession([professionInput]); 
                       }
                   }}
                   />                   
                   
                   </Box>
                   {errors.profession && <Typography color="error" variant="caption">{errors.profession}</Typography>}
           </Box>
       </Box>
    );
}

/*
                   <Select value={profession} required onChange={(e) => {
                          setProfession(e.target.value);
                          demographicsData["profession"] = e.target.value; 
                          console.log("demographics data: ", demographicsData["profession"]);
                       }} displayEmpty>
                       {professions.map((s) => (
                           <MenuItem  key={s} value={s}>
                                {s}
                           </MenuItem>
                       ))}
                   </Select>*/

/* STYLING FEATURES */
// Main header for the swarm survey
function MainHeader({ fadeAnimation }) {
  return (
    <Box sx={{    
      width: 'flex',
      height: '80%', 
      textAlign: 'center', 
      justifyContent: 'center',
      fontSize: '100px',
      fontColor: '#FFF',
      padding: '100px',
      opacity: fadeAnimation ? 1 : 0, 
      transform: fadeAnimation ? "translateY(0)" : "translateY(-50px)",
      transition: "opacity 1s ease-out, transform 1s ease-out",
    }}>
      <Typography sx={{fontFamily: "'Cormorant Garamond', Georgia, serif", fontWeight: 'bold', fontSize: '70px', alignItems: 'center', justifyContent: 'center', display: 'flex', position: 'relative', padding: '20px', color: '#000', }}>
        Welcome to the swarm complexity ranking survey!
      </Typography>
    </Box>
  );
}

/* Double arrow for complexity */
function DoubleArrow({ xpos, ypos }) {
  console.log("ranked videos length: "+Object.keys(rankedVideos).length*100);
  return (
  <Box sx={{top: ypos,
          left: xpos,
          transform: 'translate(-${xpos}, -${ypos})', position: 'absolute', }}>
  <Box sx={{
     width: 0,
     height: 0,
     borderLeft: '40px solid transparent',
     borderRight: '40px solid transparent',
     borderBottom: '80px solid #FF1919',
  }}/>

  <Box sx={{ display: 'flex', flexDirection: 'column', }}>
  <Box sx={{
     display: 'inline-block',
     flexDirection: 'column',
     top: `calc(${ypos} + ${Object.keys(rankedVideos).length/2} - 0%)`,
     transform: 'translateY(-10%)',
     left: `calc(${xpos} + 70%)`,
     position: 'absolute',
     background: '#4D6AFF',
     border: '5px solid #003399',
     borderRadius: '8px',
     textColor: '#FFF',
     padding: '5px',
     fontSize: '25px',
  }}>
  <Typography sx={{fontWeight: 'bold', fontSize: '25px', alignItems: 'center', justifyContent: 'center', display: 'flex', position: 'relative', margin: '20px', fontFamily: "'Orbitron', monospace", }}>
     Most complex
  </Typography>
  </Box>
  <Box sx={{
     transform: 'translateX(45%) translateY(20%)',
     width: 0,
     height: 0,
     marginLeft: `calc(${xpos} + 230%)`,
     borderBottom: '40px solid transparent',
     borderTop: '40px solid transparent',
     borderLeft: '80px solid #000',
     position: 'absolute'
  }}/>
  </Box>

  <Box sx={{
     width: 80,
     height: Object.keys(rankedVideos).length * 150,
     background: 'linear-gradient(rgba(255,25,25), rgba(0,0,0))',
  }}/>



  <Box sx={{ display: 'flex', flexDirection: 'column', }}>
  <Box sx={{
     display: 'inline-block',
     flexDirection: 'column',
     top: `calc(${ypos} - ${Object.keys(rankedVideos).length/2} + 10%)`,
     transform: 'translateY(-110%)',
     left: `calc(${xpos} + 70%)`,
     position: 'absolute',
     background: '#4D6AFF',
     border: '5px solid #003399',
     borderRadius: '8px',
     textColor: '#FFF',
     padding: '5px',
  }}>
  <Typography sx={{fontWeight: 'bold', fontSize: '25px', alignItems: 'center', justifyContent: 'center', display: 'flex', position: 'relative', margin: '20px', fontFamily: "'Orbitron', monospace", }}>
     Least complex
  </Typography>
  </Box>
  <Box sx={{
     transform: 'translateX(40%) translateY(-135%)',
     width: 0,
     height: 0,
     marginLeft: `calc(${xpos} + 230%)`,
     borderBottom: '40px solid transparent',
     borderTop: '40px solid transparent',
     borderLeft: '80px solid #000',
     position: 'absolute'
  }}/>
  </Box>

  <Box sx={{
     width: 0,
     height: 0,
     borderLeft: '40px solid transparent',
     borderRight: '40px solid transparent',
     borderTop: '80px solid #000',
  }}/>

  </Box>
  );
};