name: Swarm Video Sorter

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install
          npm run build
          echo "Listing all swarm-videos files in build:"
          ls -R build/swarm-videos

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          # This uses your personal admin power to bypass the Org restriction
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true